/**
 * WHAT: Validates or normalises foreign FHIR R4 Bundles structurally.
 * NOT:  Must not rewrite clinical codes or units to pass gates.
GOVERNED BY: DECISIONS.md#d1; DECISIONS.md#d2; DECISIONS.md#d6
 * CORRECTNESS: HL7 FHIR R4 structure rules (local checks); CI also runs official validator on emitted exemplars.
 */
export const R4_RESOURCE_TYPES: ReadonlySet<string> = new Set([
  'Account',
  'ActivityDefinition',
  'AdverseEvent',
  'AllergyIntolerance',
  'Appointment',
  'AppointmentResponse',
  'AuditEvent',
  'Basic',
  'Binary',
  'BiologicallyDerivedProduct',
  'BodyStructure',
  'Bundle',
  'CapabilityStatement',
  'CarePlan',
  'CareTeam',
  'CatalogEntry',
  'ChargeItem',
  'ChargeItemDefinition',
  'Claim',
  'ClaimResponse',
  'ClinicalImpression',
  'CodeSystem',
  'Communication',
  'CommunicationRequest',
  'CompartmentDefinition',
  'Composition',
  'ConceptMap',
  'Condition',
  'Consent',
  'Contract',
  'Coverage',
  'CoverageEligibilityRequest',
  'CoverageEligibilityResponse',
  'DetectedIssue',
  'Device',
  'DeviceDefinition',
  'DeviceMetric',
  'DeviceRequest',
  'DeviceUseStatement',
  'DiagnosticReport',
  'DocumentManifest',
  'DocumentReference',
  'EffectEvidenceSynthesis',
  'Encounter',
  'Endpoint',
  'EnrollmentRequest',
  'EnrollmentResponse',
  'EpisodeOfCare',
  'EventDefinition',
  'Evidence',
  'EvidenceVariable',
  'ExampleScenario',
  'ExplanationOfBenefit',
  'FamilyMemberHistory',
  'Flag',
  'Goal',
  'GraphDefinition',
  'Group',
  'GuidanceResponse',
  'HealthcareService',
  'ImagingStudy',
  'Immunization',
  'ImmunizationEvaluation',
  'ImmunizationRecommendation',
  'ImplementationGuide',
  'InsurancePlan',
  'Invoice',
  'Library',
  'Linkage',
  'List',
  'Location',
  'Measure',
  'MeasureReport',
  'Media',
  'Medication',
  'MedicationAdministration',
  'MedicationDispense',
  'MedicationKnowledge',
  'MedicationRequest',
  'MedicationStatement',
  'MedicinalProduct',
  'MedicinalProductAuthorization',
  'MedicinalProductContraindication',
  'MedicinalProductIndication',
  'MedicinalProductIngredient',
  'MedicinalProductInteraction',
  'MedicinalProductManufactured',
  'MedicinalProductPackaged',
  'MedicinalProductPharmaceutical',
  'MedicinalProductUndesirableEffect',
  'MessageDefinition',
  'MessageHeader',
  'MolecularSequence',
  'NamingSystem',
  'NutritionOrder',
  'Observation',
  'ObservationDefinition',
  'OperationDefinition',
  'OperationOutcome',
  'Organization',
  'OrganizationAffiliation',
  'Parameters',
  'Patient',
  'PaymentNotice',
  'PaymentReconciliation',
  'Person',
  'PlanDefinition',
  'Practitioner',
  'PractitionerRole',
  'Procedure',
  'Provenance',
  'Questionnaire',
  'QuestionnaireResponse',
  'RelatedPerson',
  'RequestGroup',
  'ResearchDefinition',
  'ResearchElementDefinition',
  'ResearchStudy',
  'ResearchSubject',
  'RiskAssessment',
  'RiskEvidenceSynthesis',
  'Schedule',
  'SearchParameter',
  'ServiceRequest',
  'Slot',
  'Specimen',
  'SpecimenDefinition',
  'StructureDefinition',
  'StructureMap',
  'Subscription',
  'Substance',
  'SubstanceNucleicAcid',
  'SubstancePolymer',
  'SubstanceProtein',
  'SubstanceReferenceInformation',
  'SubstanceSourceMaterial',
  'SubstanceSpecification',
  'SupplyDelivery',
  'SupplyRequest',
  'Task',
  'TerminologyCapabilities',
  'TestReport',
  'TestScript',
  'ValueSet',
  'VerificationResult',
  'VisionPrescription',
]);

export const R4_REQUIRED_ELEMENTS: Readonly<Record<string, readonly string[]>> = {
  "Account": ['status'],
  "ActivityDefinition": ['status'],
  "AdverseEvent": ['actuality', 'subject'],
  "AllergyIntolerance": ['patient'],
  "Appointment": ['status', 'participant'],
  "AppointmentResponse": ['appointment', 'participantStatus'],
  "AuditEvent": ['type', 'recorded', 'agent', 'source'],
  "Basic": ['code'],
  "Binary": ['contentType'],
  "BodyStructure": ['patient'],
  "Bundle": ['type'],
  "CapabilityStatement": ['status', 'date', 'kind', 'fhirVersion', 'format'],
  "CarePlan": ['status', 'intent', 'subject'],
  "CatalogEntry": ['orderable', 'referencedItem'],
  "ChargeItem": ['status', 'code', 'subject'],
  "ChargeItemDefinition": ['url', 'status'],
  "Claim": ['status', 'type', 'use', 'patient', 'created', 'provider', 'priority', 'insurance'],
  "ClaimResponse": ['status', 'type', 'use', 'patient', 'created', 'insurer', 'outcome'],
  "ClinicalImpression": ['status', 'subject'],
  "CodeSystem": ['status', 'content'],
  "Communication": ['status'],
  "CommunicationRequest": ['status'],
  "CompartmentDefinition": ['url', 'name', 'status', 'code', 'search'],
  "Composition": ['status', 'type', 'date', 'author', 'title'],
  "ConceptMap": ['status'],
  "Condition": ['subject'],
  "Consent": ['status', 'scope', 'category'],
  "Coverage": ['status', 'beneficiary', 'payor'],
  "CoverageEligibilityRequest": ['status', 'purpose', 'patient', 'created', 'insurer'],
  "CoverageEligibilityResponse": ['status', 'purpose', 'patient', 'created', 'request', 'outcome', 'insurer'],
  "DetectedIssue": ['status'],
  "DeviceMetric": ['type', 'category'],
  "DeviceRequest": ['intent', 'code[x]', 'subject'],
  "DeviceUseStatement": ['status', 'subject', 'device'],
  "DiagnosticReport": ['status', 'code'],
  "DocumentManifest": ['status', 'content'],
  "DocumentReference": ['status', 'content'],
  "EffectEvidenceSynthesis": ['status', 'population', 'exposure', 'exposureAlternative', 'outcome'],
  "Encounter": ['status', 'class'],
  "Endpoint": ['status', 'connectionType', 'payloadType', 'address'],
  "EpisodeOfCare": ['status', 'patient'],
  "EventDefinition": ['status', 'trigger'],
  "Evidence": ['status', 'exposureBackground'],
  "EvidenceVariable": ['status', 'characteristic'],
  "ExampleScenario": ['status'],
  "ExplanationOfBenefit": ['status', 'type', 'use', 'patient', 'created', 'insurer', 'provider', 'outcome', 'insurance'],
  "FamilyMemberHistory": ['status', 'patient', 'relationship'],
  "Flag": ['status', 'code', 'subject'],
  "Goal": ['lifecycleStatus', 'description', 'subject'],
  "GraphDefinition": ['name', 'status', 'start'],
  "Group": ['type', 'actual'],
  "GuidanceResponse": ['module[x]', 'status'],
  "ImagingStudy": ['status', 'subject'],
  "Immunization": ['status', 'vaccineCode', 'patient', 'occurrence[x]'],
  "ImmunizationEvaluation": ['status', 'patient', 'targetDisease', 'immunizationEvent', 'doseStatus'],
  "ImmunizationRecommendation": ['patient', 'date', 'recommendation'],
  "ImplementationGuide": ['url', 'name', 'status', 'packageId', 'fhirVersion'],
  "Invoice": ['status'],
  "Library": ['status', 'type'],
  "Linkage": ['item'],
  "List": ['status', 'mode'],
  "Measure": ['status'],
  "MeasureReport": ['status', 'type', 'measure', 'period'],
  "Media": ['status', 'content'],
  "MedicationAdministration": ['status', 'medication[x]', 'subject', 'effective[x]'],
  "MedicationDispense": ['status', 'medication[x]'],
  "MedicationRequest": ['status', 'intent', 'medication[x]', 'subject'],
  "MedicationStatement": ['status', 'medication[x]', 'subject'],
  "MedicinalProduct": ['name'],
  "MedicinalProductIngredient": ['role'],
  "MedicinalProductManufactured": ['manufacturedDoseForm', 'quantity'],
  "MedicinalProductPackaged": ['packageItem'],
  "MedicinalProductPharmaceutical": ['administrableDoseForm', 'routeOfAdministration'],
  "MessageDefinition": ['status', 'date', 'event[x]'],
  "MessageHeader": ['event[x]', 'source'],
  "MolecularSequence": ['coordinateSystem'],
  "NamingSystem": ['name', 'status', 'kind', 'date', 'uniqueId'],
  "NutritionOrder": ['status', 'intent', 'patient', 'dateTime'],
  "Observation": ['status', 'code'],
  "ObservationDefinition": ['code'],
  "OperationDefinition": ['name', 'status', 'kind', 'code', 'system', 'type', 'instance'],
  "OperationOutcome": ['issue'],
  "PaymentNotice": ['status', 'created', 'payment', 'recipient', 'amount'],
  "PaymentReconciliation": ['status', 'created', 'paymentDate', 'paymentAmount'],
  "PlanDefinition": ['status'],
  "Procedure": ['status', 'subject'],
  "Provenance": ['target', 'recorded', 'agent'],
  "Questionnaire": ['status'],
  "QuestionnaireResponse": ['status'],
  "RelatedPerson": ['patient'],
  "RequestGroup": ['status', 'intent'],
  "ResearchDefinition": ['status', 'population'],
  "ResearchElementDefinition": ['status', 'type', 'characteristic'],
  "ResearchStudy": ['status'],
  "ResearchSubject": ['status', 'study', 'individual'],
  "RiskAssessment": ['status', 'subject'],
  "RiskEvidenceSynthesis": ['status', 'population', 'outcome'],
  "Schedule": ['actor'],
  "SearchParameter": ['url', 'name', 'status', 'description', 'code', 'base', 'type'],
  "ServiceRequest": ['status', 'intent', 'subject'],
  "Slot": ['schedule', 'status', 'start', 'end'],
  "StructureDefinition": ['url', 'name', 'status', 'kind', 'abstract', 'type'],
  "StructureMap": ['url', 'name', 'status', 'group'],
  "Subscription": ['status', 'reason', 'criteria', 'channel'],
  "Substance": ['code'],
  "SupplyRequest": ['item[x]', 'quantity'],
  "Task": ['status', 'intent'],
  "TerminologyCapabilities": ['status', 'date', 'kind'],
  "TestReport": ['status', 'testScript', 'result'],
  "TestScript": ['url', 'name', 'status'],
  "ValueSet": ['status'],
  "VerificationResult": ['status'],
  "VisionPrescription": ['status', 'created', 'patient', 'dateWritten', 'prescriber', 'lensSpecification'],
};
